
version: '3.4'
services:
  db:
    image: "arm32v7/postgres"
    restart: always
    networks: 
      - db
    volumes:
      - type: volume
        source: zabbix-db-volume
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - type: volume
        source: zabbix-init-volume
        target: /docker-entrypoint-initdb.d 
        volume:  
          nocopy: true
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix_admin
      POSTGRES_PASSWORD: password  
      PGDATA: /var/lib/postgresql/data

  zabbix:
    image: 10.5.11.12:5000/zabbix-aio
    build: zabbix-aio
    networks:
      - db 
    ports:
      - 80:80
      
volumes:
  zabbix-init-volume:
    driver_opts:
      type: "nfs"
      o: "addr=10.5.11.20,nolock,soft,rw"
      device: ":/export/Volumes/$HOST/zabbix/init"
  zabbix-db-volume:
    driver_opts:
      type: "nfs"
      o: "addr=10.5.11.20,nolock,soft,rw"
      device: ":/export/Volumes/$HOST/zabbix/db"



networks:
  db:
    driver: overlay      
