---

#
# install docker compose 
#
#
#
#

- name: install base packages
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - htop  
    - vim
    - curl
    - tmux



- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc 
    state: present


- apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian stretch contrib
    state: present


- name: update apt cache
  apt:
    update_cache: yes
    


- name: install docker-ce
  apt: 
    name: virtualbox-6.0=6.0.4-128413~Debian~stretch  
    state: present
  tags: packages

