FROM arm32v7/ubuntu:bionic

ENV DEBIAN_FRONTEND noninteractive


RUN apt-get update && apt-get install  -y tor




#CMD [ "ddclient", "-daemon", "3", "-foreground", "-v", "-file", "/etc/ddclient.conf" ]






